services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/var/www
      - /var/www/frontend/node_modules
    working_dir: /var/www/frontend
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm start"]

networks:
  symfony_network:
    driver: bridge
